# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companie',
            old_name='compa',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='com',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='em',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='employ',
            new_name='employee',
        ),
    ]
