# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
