# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160425_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
