# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160418_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='time_in',
        ),
        migrations.AddField(
            model_name='log',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
