# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20160426_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
