# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20160427_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
